### PR TITLE
Fresh after 2to3

### PR DESCRIPTION
**Pull request by bsathian**

### CODE REVIEW

**Comment by aminnj** [comment]
is it ready to be merged? I don't see any problems so far

**Comment by bsathian** [comment]
Examples.py breaks because pythom does not allow relative imports within a
module anymore, so you can't get away calling import utils in plottery.py
and expect it to be imported as a module outside. Other than that this
works like a charm.

Balaji

**Comment by aminnj** [comment]
I see. if you do
```diff
diff --git a/examples.py b/examples.py
index ed850fd..b42e4ec 100644
--- a/examples.py
+++ b/examples.py
@@ -1,6 +1,6 @@
+import plottery as ply
 import ROOT as r
 import os
-import plottery as ply

 """
 0 to print out all possible options and their defaults
--- a/plottery.py
+++ b/plottery.py
@@ -1,8 +1,10 @@
 # coding: utf-8

+from __future__ import absolute_import
+
 import os
 import ROOT as r
-import plottery.utils as utils
+import utils
 from array import array
 import math
 from itertools import cycle
```

then it should work in python2.7 as well. if you agree and add it, i'll merge :)

..basically moving plottery import to top and adding one line for the absolute_import

**Comment by bsathian** [comment]
Okay I'll add it tomorrow and then you can merge 🙂

**Comment by bsathian** [comment]
I removed the absolute imports, but examples.py need to be run as a module
now (python -m plottery.examples from a directory outside) to work in
python3. I have updated the readme for that. In addition, the python3
branch also works with python2 now.

The one you suggested is failing in python3 because python3 cannot realize
the fact that utils is along with plottery.py in the same folder (because
implicit relative imports has been discontinued). However, examples.py will
work because they're all in the same folder (examples, plottery and utils).
Absolute import also fails because examples.py does not know what plottery
is, and explicit relative import (from . import plottery) fails with
examples.py because python now does not know what "." means, but it works
for other plotting scripts from outside. However running examples.py as a
module outside won't have issues with explicit relative imports. This works
even with python2.7 without the __future__ import

Balaji

**Comment by aminnj** [comment]
That's makes sense to me. Thanks for also updating the README!

**Pull request merged**
